### ISSUE TITLE
Build QA Environment 

### ISSUE THREAD

**Issue by jennifershivers** [OpenConceptLab/DATIM-Metadata-Project#1]
Build QA environment for the DATIM.  Specifications are as defined below:  
![specs](https://user-images.githubusercontent.com/13437212/28781661-ccaa1618-75d8-11e7-8136-19660b46cdb1.png)

**Comment by paynejd** [comment]
@rkorytkowski Will this be done on Monday?

**Comment by rkorytkowski** [comment]
Done! Added docs at https://github.com/OpenConceptLab/oclapi/commit/25bd55c2344f961495c9716202b34d6e50939a05
