### ISSUE TITLE
Remodel relationship between source version, concept and mappings

### ISSUE THREAD

**Issue by rkorytkowski** [OpenConceptLab/DATIM-Metadata-Project#102]
Currently concepts and mappings belonging to a source version are stored as a list of ids within SourceVersion object. The list of concepts in CIEL source is almost 53k, which introduces significant performance bottleneck when it comes to persisting and fetching the SourceVersion object from db. The list of mappings is a few times bigger than that!

To fix that I'll introduce ConceptSourceVersion object which stores concept_version_id and source_version_id with a proper db index for fast querying. It should perform great regardless of how many concepts or sources we will have. Similarly I'll introduce MappingSourceVersion with mapping_version_id and source_version_id fields.

**Comment by rkorytkowski** [comment]
Collections have the same issue, but will not be handled as part of this remodeling unless there is a dependency in code.

**Comment by rkorytkowski** [comment]
@paynejd, it will be less work, if we can drop concepts and mappings and import them again using import scripts. Do you feel we can do that? Otherwise I'll have to write a migration script, which should not be hard, but can take extra time.

**Comment by paynejd** [comment]
Are you wanting to drop the content just this once or is that what would be done each time that an import is performed?

**Comment by rkorytkowski** [comment]
Just this once.

**Comment by paynejd** [comment]
Yeah, that's fine. Go ahead and move forward with that. We can then
re-import the starter content, CIEL, and Ethiopia when it's ready.

**Comment by rkorytkowski** [comment]
All work committed to https://github.com/OpenConceptLab/oclapi/pull/535 (not yet ready for merging)

Right now I'm testing migration on the production db...

**Comment by rkorytkowski** [comment]
It's been merged and successfully deployed to qa.

I've also deployed it to staging, which is getting migrated right now (thus unresponsive) and should be available in 1-2 hours.

**Comment by rkorytkowski** [comment]
Reworked my solution. Basically storing source_version_ids as a list on ConceptVersion and MappingVersion. I use atomic operations for populating and removing items from a list to make it perform well and correct in concurrent writes. The original solution did not perform in some queries e.g. paging through all concept versions in a source, because in mongodb joins are of limited use (only supported as aggregations and not supported in django nonrel). We had to pull all concept version ids of a source even if we only wanted to return 10 concept versions of a source. The current solution should perform well unless a concept version is included in thousands of versions of a source, which is unlikely to happen. We could consider archiving older versions, if we ever hit that limit.

The change is deployed to qa and staging.

**Comment by rkorytkowski** [comment]
Deployed to production!
