### ISSUE TITLE
Setup continuous integration environment

### ISSUE THREAD

**Issue by jennifershivers** [OpenConceptLab/DATIM-Metadata-Project#11]
Currently using GoCD (see www.gocd.org) setup on the QA server at gocd.openconceptlab.org. It uses GitHub login for authentication, so members of this group should be able to log in at the above URL to view the configuration. GoCD configuration is available in this repository: https://github.com/OpenConceptLab/ocl_build_pipeline

**Comment by rkorytkowski** [comment]
I'm not able to log in using github... First it showed me a login page and I clicked the github icon to authorize OpenConceptLab to access my github, which seemed to have worked. Now when I click the github icon it doesn't return any errors, but keeps redirecting me to the login page...

**Comment by rkorytkowski** [comment]
@paynejd I think you need to setup access for individual github users as explained at https://github.com/OpenConceptLab/ocl_build_pipeline#user-management

**Comment by paynejd** [comment]
@rkorytkowski Just added you directly to GoCD. Let me know if this works

**Comment by rkorytkowski** [comment]
It worked, thanks!

**Comment by paynejd** [comment]
Going with Bamboo (also known as OurCI.com) instead of GoCD

Configuration for this is still ongoing

**Comment by rkorytkowski** [comment]
Setup at https://ci.openmrs.org/browse/OCL
