### ISSUE TITLE
'next' response header returns localhost IP instead of resolved domain name

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/DATIM-Metadata-Project#111]
For REST API queries that return lists, there is always a 'next' header in the response. The value is 'None' if there are no more results, but something like this if there are more results:

http://127.0.0.1:8000/orgs/PEPFAR/collections/?verbose=true&page=2

The above response is from oclapi-qa.openmrs.org. As you can see, it is using the local IP, when it should say "https://oclapi-qa.openmrs.org/..."

**Comment by rkorytkowski** [comment]
Deployed to qa. See https://api.qa.openconceptlab.org/orgs/OCL/sources/Locales/concepts/?limit=5

**Comment by paynejd** [comment]
Tested on QA and this looks good!

**Comment by rkorytkowski** [comment]
Deployed to staging and production!
