### ISSUE TITLE
Fix integration tests related to source and collection version export

### ISSUE THREAD

**Issue by davetrig** [OpenConceptLab/DATIM-Metadata-Project#113]
The integration tests for Source Version and Collection Version exports do not correctly test POST requests.  

Tests that should issue POSTs, other than tests for HEAD or nonexistent versions are issuing GETs, and not POSTs.  Issuing a POST results in a "401: Authentication credentials were not submitted" response.

The appropriate method of API authentication needs to be established, and the POST tests need to actually tests POSTs.

All tests in question exist in oclapi/djanjo-nonrel/ocl/integration_tests/tests/all.py.

**Comment by davetrig** [comment]
I finally worked out why the tests were not working.  I applied the fix to all export POST tests, and submitted a pull request.

**Comment by rkorytkowski** [comment]
Merged https://github.com/OpenConceptLab/oclapi/pull/536

**Comment by rkorytkowski** [comment]
Waiting for results from CI...

**Comment by rkorytkowski** [comment]
https://ci.openmrs.org/browse/OCL-OA-77
