### ISSUE TITLE
Fix production confirmation email

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/DATIM-Metadata-Project#114]
Confirmation email on staging works correctly. On production, the link in the email still says "ocl.openmrs.org":
![image](https://user-images.githubusercontent.com/1189689/31031970-56ae9e28-a528-11e7-8dd6-f4ceebaa3386.png)

**Comment by rkorytkowski** [comment]
The fix wasn't pushed to production... Should work once https://ci.openmrs.org/deploy/viewDeploymentResult.action?deploymentResultId=96206911 is done

**Comment by paynejd** [comment]
Closing since this is duplicate
