### ISSUE TITLE
Source version exports sometimes return an invalid "mappings" field

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/DATIM-Metadata-Project#116]
Two times now, an export was returned that looked something like this:
{
"type": "Source Version",
"mappings": [,,,,,]
...
}

The brackets with just a list of commas is what is actually in the file.

**Comment by rkorytkowski** [comment]
I've just deployed #102 to staging. It's getting migrated now and should be available soon. Let's see, if we experience the error after those changes.

**Comment by rkorytkowski** [comment]
I'm taking it back to backlog. Please ping me if you see this error again.

**Comment by paynejd** [comment]
This error just popped up again. It's in the latest version of the MER source:
https://staging.openconceptlab.org/orgs/PEPFAR/sources/MER/v2017-10-13T100044.037131/

See the last 100 characters of this attached file...

[ocl-orgs-PEPFAR-sources-MER-raw.zip](https://github.com/OpenConceptLab/DATIM-Metadata-Project/files/1388294/ocl-orgs-PEPFAR-sources-MER-raw.zip)

**Comment by rkorytkowski** [comment]
Seems like mappings were not added properly to the source version... https://staging.openconceptlab.org/orgs/PEPFAR/sources/MER/v2017-10-13T100044.037131/mappings/

Unfortunately, we didn't catch any related error in logs... We are deleting logs every deploy and it must have happened before a deploy. I need to make the logs persistent.

**Comment by paynejd** [comment]
So recreating the source version should theoretically fix these types of
errors if they pop up again?

**Comment by rkorytkowski** [comment]
Yes, that's the work around.

**Comment by paynejd** [comment]
Adding this here for posterity...

I ran the sync script for the newly published DATIM content. It created a new source version and the same thing happened again where the mappings failed to be added into the new source version. Here's the source version that is coming up with zero mappings:

https://staging.openconceptlab.org/orgs/PEPFAR/sources/MER/v2017-10-19T230550.808243/mappings/

There are 8,190 mappings in the source head:

https://staging.openconceptlab.org/orgs/PEPFAR/sources/MER/HEAD/mappings/

From @rkorytkowski ---
There's no error in logs :/ I will need to load a db locally and try to reproduce it with a debugger... I wonder if it might be, because of the '.' in the version format: v2017-10-19T230550.808243 I've created https://staging.openconceptlab.org/orgs/PEPFAR/sources/MER/v2017-10-20/ and https://staging.openconceptlab.org/orgs/PEPFAR/sources/MER/v2017-10-20T230550.808243 to see if it is the issue.

**Comment by rkorytkowski** [comment]
I was not able to reproduce it locally, but identified that the broken version had no parent nor previous version set. I haven't determined why exactly, because code is intricate. I made this commit https://github.com/OpenConceptLab/oclapi/commit/fe5bd782e6bfaa19ca3aac1f6f7d0ca5baf79df3, which is exactly how concepts are copied to a new version and should at least work even if the parent and previous version fields are not set correctly.

**Comment by rkorytkowski** [comment]
I'll push to stg as soon as it reaches qa.

**Comment by rkorytkowski** [comment]
Pushed to stg and prd. Please let me know if you experience the error again. Otherwise it can be closed.

**Comment by paynejd** [comment]
Moving this to Sprint #7 for now --- @rkorytkowski What are your thoughts for closing this out?

**Comment by rkorytkowski** [comment]
I'd close it and reopen if you observe it again.

**Comment by paynejd** [comment]
closing for now...
