### ISSUE TITLE
Are there additional attributes available in DHIS2 that are not in ZenDesk that will be stored in OCL?

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/DATIM-Metadata-Project#12]
1. * Confirm if the metadata format on ZenDesk is the same as we'll get from DHIS2? Or are there missing fields?
2. * Can DHIS2 provide diffs to metadata sets or only the full set of metadata?
3. * What formats can we get metadata from DHIS2 in?
4. * Are older lists available in a DHIS2 instance that we could query?

Notes from conversation with Vlad (ICF) about these questions is here:
https://docs.google.com/document/d/1RHGJ8uNJgleAjMuN4-zPdYzm860g4pxKkP4xwD3diwA/edit#

**Comment by paynejd** [comment]
Ideally, we want to be able to query DATIM DHIS2 for the following:
* Unique list of indicators regardless of type & code list (and maybe period), with fields that indicate the the type
* Unique list of disaggregation options
* Full list of mechanisms
* List of disaggregation options mapped to indicators **across all code lists**
* List of indicators mapped to code lists **across all code lists**
* Full list of SIMS data elements per version
* For all above lists, ability to get the diff (new, updated, retired)

Our process (potentially scheduled/orchestrated by OpenHIM):
* Fetch CSV for one or more of the above lists
* (optional) Pre-processing - i.e. normalizing locally, etc.
* Run CSV-->JSON conversion script to get OCL-formatted JSON file
* (optional) Run additional processing - e.g. if we can't get access to diffs, this could perform a diff directly against OCL
* Import into OCL using flex importer

NOTE: The above integration process will look different if we can get diffs

Anything else?

**Comment by paynejd** [comment]
Other questions:
* Does the mechanisms list in DATIM represent the full list of mechanisms from FACTS Info, or just the subset relevant to PEPFAR?

**Comment by jennifershivers** [comment]
Per investigations, there are no known fields that need to be added to the ZenDesk lists at this time.  The DATIM process was to add what people requested.  The mechanisms lists that were missing items have been updated.

**Comment by jennifershivers** [comment]
None known at this time.
