### ISSUE TITLE
Setup SSL for web, API, GoCD, and IOL

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/DATIM-Metadata-Project#13]
Currently using Let's Encrypt for SSL certificates and Certbot (on production) to automate registration/renewal of the certificate. QA and Staging use simple cron jobs for certificate renewal, but they do not work reliably.

**Comment by bmamlin** [comment]
I fixed all the existing servers and set up cerbot to auto-renew by adding this file with permissions 755:

**/etc/cron.weekly/certbot-renew**
```
#!/bin/sh
set -e

certbot renew -q --post-hook "service nginx reload"
```

I also tweaked the nginx configuration to use this pattern for non-SSL connections to support certbot challenge and redirect all other requests to SSL:
```
server {
    listen 80;
    server_name <subdomain>.openconceptlab.org;
    location '/.well-known/acme-challenge' {
        default_type "text/plain";
        root        /var/www/openconceptlab;
    }
    location / {
        return 301 https://$host$request_uri;
    }
}
```
