### ISSUE TITLE
Underscores must be allowed in concept identifiers

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/DATIM-Metadata-Project#16]
Underscores must be allowed in the concept ID. Periods and hyphens are already supported. Note that hyphens, periods, and underscores are all already supported in the concept names/synonyms, just not in the ID.

Modify user/tech documentation and help text in the UI to make it clear which characters are allowed.

**Comment by davetrig** [comment]
@paynejd, Please confirm that the highlighted field in the screenshot below is the Concept ID in question, and that this is the only field that this ticket pertains to.

Also, please confirm that allowing underscores is the only change to the validation of this field, and any other existing validations or restrictions (if any) are to remain intact.

![image](https://user-images.githubusercontent.com/10239390/29106253-0e1d9208-7ca2-11e7-85bc-05f0ce87456b.png)

**Comment by paynejd** [comment]
@davetrig You are correct that the concept ID is the only relevant field
for this ticket. In the underlying model, this is simply the "id" field.
Also, underscores is the only needed change. I tested hyphens and periods
before creating this ticket, and they are both already supported.

**Comment by davetrig** [comment]
The scope of this update is larger than originally thought.  This being the ID of an object, it becomes part of the RESTful URL identifying the object in the web application.  Those URLs are filtered and matched using regular expressions that also do not include underscores, and those regular expressions appear to be hard-coded in many places in the web application.

**Comment by davetrig** [comment]
Code changes complete in oclapi and ocl_web projects, and pull requests created.

**Comment by davetrig** [comment]
I have added the integration test for concept id with underscore, and submitted a pull request under the oclapi project.

**Comment by rkorytkowski** [comment]
All good!
