### ISSUE TITLE
Setup pushing logs to sentry

### ISSUE THREAD

**Issue by rkorytkowski** [OpenConceptLab/DATIM-Metadata-Project#163]
Sentry is a service to gather and process server logs and send out notifications. We need it to track errors without having to go through log files on servers. It can be easily integrated as a logger handler, see: https://docs.sentry.io/clients/python/integrations/django/

**Comment by rkorytkowski** [comment]
Created https://sentry.io/openconceptlab

@paynejd, please create a personal account on sentry and I'll add you to the openconceptlab org so you can see reported errors and get notifications.

**Comment by paynejd** [comment]
Just created!

**Comment by rkorytkowski** [comment]
We're using a shared admin@openconceptlab.org account, which also receives e-mail alerts about ERRORs. Deployed to qa and staging (in progress). There's 10 000 monthly events limit on the free account. We'll probably need to tweak logging further to disable logging some of errors, e.g. 40* should be logged as WARNINGS, not ERRORs and not reaching sentry (thus not wasting the limit)

**Comment by rkorytkowski** [comment]
I'll disable e-mail notifications for now until their amount goes down (same errors are not e-mailed more than once).
