### ISSUE TITLE
Prepare indicator mapping spreadsheet for import

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/DATIM-Metadata-Project#165]

**Comment by jennifershivers** [comment]
I have one country done here https://docs.google.com/spreadsheets/d/12Of0hPPdgknSnzvsE_mmvPUaBa4Zz7U2VjmyEwTgSRc/edit#gid=1744234448

I am working on a second country.  Note that I tried to make up reasonable looking names for the indicators and disagregates while keeping the mapping in tact.

**Comment by jennifershivers** [comment]
@paynejd I have two MOH indicator mapping examples in that spreadsheet now.

**Comment by paynejd** [comment]
thank you jennifer!
