### ISSUE TITLE
Periods must be allowed in concept custom attribute names

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/DATIM-Metadata-Project#17]
Concept custom attributes already support hyphens and underscores, but also need to support periods (".")

It appears that periods are already supported in the UI, but not in the API level (though this needs to be confirmed)

Modify documentation and help text in the UI to make it clear which characters are allowed.

**Comment by paynejd** [comment]
Need follow up technical discussion on this ticket

**Comment by rkorytkowski** [comment]
Please see my comments on the PR.

**Comment by greshje** [comment]
I'm on it

**Comment by rkorytkowski** [comment]
Please add tests to prove creating new, updating and fetching a concept with custom attribute names is working. I'm not confident to merge the code without tests. It is tricky.

**Comment by rkorytkowski** [comment]
All good! Thanks!
