### ISSUE TITLE
Briefly map out how FHIR API could be used for code validation/transformation

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/DATIM-Metadata-Project#170]
include high level description of activities
and example of FHIR API

**Comment by cmac35** [comment]
@jennifershivers Thanks for offering to provide an example of the level of detail Mike likes to see. Can you post it here. Thanks in advance

**Comment by cmac35** [comment]
---Draft for internal review---
@jennifershivers and @paynejd - Right level of detail? I can also put together some slides on current FHIR functionality and how it may align with their use case.

1. Business and Functional Gap Analysis - Three (3) Business Days
- Review the FHIR Code System, ValueSet and ConceptMap resources and the Validate and Translate operations. 
- Compare the existing OCL API and REST services to identify gaps in OCL
2. Development of functionality to provide FHIR Terminology Services - Four (4) Business Days 
- Limited to functionality required to support PEPFAR use case of translating between PEPFAR and MoH indicator concepts
- Develop FHIR formatted responses (XML and JSON) 
3. Integration and User Acceptance Testing - Two (2) Business Days

**Comment by jennifershivers** [comment]
Yes.  At the top provide a time frame of when we would have this done.  Also note that the transaction specification that we want to use does alraedy exist in FHIR.  (At least that was my understanding from conversations with Jack a few months ago.)  May want to give a link to that and note the section to look at.  ..... Sorry for forgetting to get you an example.  :-)

**Comment by cmac35** [comment]
Added the following to the slides for 10/30 meeting with Mike:

Time Frame - Three (3) calendar weeks
Total Level of Effort - Ten (10) business days
1)Business and Functional Gap Analysis - Four(4) Business Days
Review the FHIR CodeSystem, ValueSet and ConceptMap resources and the applicable operations.
Compare the existing OCL API and REST services to identify gaps in OCL
Confer with OpenHIE Terminology Services and/or FHIR Terminology Services communities
2) Development of functionality to provide FHIR Terminology Services - Four (4) Business Days
Limited to functionality required to support PEPFAR use case of translating between PEPFAR and MoH indicator concepts
Develop FHIR formatted responses (XML and JSON)
3) Integration and User Acceptance Testing - Two (2) Business Days
UAT testing with PEPFAR
OpenHIM Mediator integration

**Comment by paynejd** [comment]
closing this out and creating tasks for the actual work.
