### ISSUE TITLE
OCL functionality rapid assessment

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/DATIM-Metadata-Project#19]
Apelon to conduct rapid assessment of OCL to recommend features that may be blockers for phase 1 of the clearinghouse project based on their experience with terminology services elsewhere.

**Comment by cmac35** [comment]
Items for consideration: 
- Ability to view changes over time between two selected versions - Though a log of changes is visible in the History Tab, there is no visual/graphical representation of changes at a concept level. Specifically, there is no easily consumable visual of what a concept looked like at two points in time (e.g., PEPFAR COP17 FY Q1 vs COP17 FY Q2), If the author does not provide a detailed comment on the change that was made, the users must look at each concept version separately and manually compare. As making it easier for users to note what changed between versions is one of the advantages of using a TS behind the Clearinghouse, this functionality seemingly would go a long way in terms of value add for users.
- Within the user interface, ability to search for concepts with an Attribute or Custom Attribute value (e.g., all concepts with Custom Attribute Indicator Type = Result). The results of the search could then be used to define a collection by the user within the interface.
- From concept details view, ability to see which Collections in which the concept is a member

Items for consideration a bit further down the road:

- Ability to Template Custom Attribute types within a source - as we envision meta data elements being authored in OCL, currently on each concept an author requires the same Custom Attributes they must create each Custom Attribute (type and name). With a Template available, authoring effort is reduced and risk is mitigated that a required custom attribute is missed during editing.
- Within the user interface, ability to define a collection by a attribute or custom attribute value (e.g., create a collection of all MER Indicator concepts with the custom attribute "Indicator Type" = "Result).

**Comment by paynejd** [comment]
Thanks @cmac35. These are good suggestions and I'll go ahead and create tickets in the backlog for the first 3. Regarding the diff visualizer, we have a Google Summer of Code student who has been working on a diff feature that we may be able to review soon.
