### ISSUE TITLE
Design OHIE Web Page for initial feedback & deployment

### ISSUE THREAD

**Issue by jennifershivers** [OpenConceptLab/DATIM-Metadata-Project#2]
To do for this is in Basecamp and details will be managed there.  https://3.basecamp.com/3677712/buckets/3738637/todos/596511359

Jennifer will coordinate with Jamie and Tim to get this done.

**Comment by paynejd** [comment]
As per an excellent suggestion from @bmamlin, @jennifershivers is following up with Tim Briscoe from RI to see if we can simply recreate the exact ZenDesk page with OHIE branding with links that still point to PEPFAR's global DATIM DHIS2 server for metadata (or other PEPFAR-managed servers for documents). We could then showcase that to PEPFAR within the next week or 2, and then one-by-one switch links over to the OHIE clearinghouse as content/functionality is ready.

**Comment by paynejd** [comment]
Plan is to review a first draft by Wed, Aug 9, then do a small round of revisions before presenting to PEPFAR on Mon, Aug 14.

**Comment by paynejd** [comment]
Jon to do final revision of the OHIE Clearinghouse page and will coordinate with Tim

**Comment by paynejd** [comment]
Clearinghouse text revised and added to this gdoc:
https://docs.google.com/document/d/1O_9sH1kdV3vs_RGZU_JeOq481FAwJcF7DnNBaPyaNGs/edit#heading=h.9oove0cz4f30
