### ISSUE TITLE
Draft integration plan between DATIM Global and OHIE Clearinghouse

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/DATIM-Metadata-Project#20]
High-level sync process (scheduled & managed by OpenHIM):
* Fetch a code lists (full list or "modified since" -- DHIS2 provides both of these)
* Pre-processing - i.e. normalizing locally, etc. as needed
* Run conversion script to get OCL-formatted JSON file
* Import into OCL

The current thinking is that OpenHIM would serve as the interoperability layer between DATIM and the clearinghouse through:
* Defining one sync process for each of the metadata sets that can do each step as outlined above in the high-level sync process
* Scheduling each sync process to run on a regular schedule (e.g. nightly, weekly, monthly, quarterly)
* Ability for selected administrators to manually run a sync process
* Tracking each execution of a sync process including maintaining the log output for each

A sync process needs to be defined for each of the metadata sets:
* Targets
* Results
* Disaggregation options
* Mechanisms
* SIMS
* Org units

Ideally, we want to be able to query DATIM DHIS2 for the following, but that the actual approach will be determined by supported functionality in the DHIS2 API:
* Unique list of indicators regardless of type (result or target), code list, or maybe period, with fields that indicate the specific dataset
* Unique list of disaggregation options
* Full list of mechanisms
* List of disaggregation options mapped to indicators **across all code lists** --> this request will be used to create the mappings between indicators and disaggregation options
* List of indicators mapped to code lists **across all code lists** (I think these are referred to as "datasets" within DHIS2)
* Full list of SIMS data elements per version
* For all above lists, ability to get only those records that have been modified since a specified date

The documentation for this can be in a Google slide deck, doc, or spreadsheet.

**Comment by jennifershivers** [comment]
@maurya is working on a draft process.  We should be ready to share internally this week and at the next OHIE architecture call.

**Comment by paynejd** [comment]
FYI here is the link to the FHIR documentation that may be relevant for this: https://www.hl7.org/FHIR/measure.html

**Comment by maurya** [comment]
Draft Integration Plan - 
https://docs.google.com/presentation/d/18EE7tTHHmg64XIIeWc38lfL_VoIpCTBhaLF_zBYGMhg/edit#slide=id.g243a0f1e14_0_12
