### ISSUE TITLE
Draft plan for clearinghouse handling html/download requests from the Landing Page

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/DATIM-Metadata-Project#21]
The Landing Page will provide links to each DATIM code list similar to what is available in the current ZenDesk: https://datim.zendesk.com/hc/en-us/articles/115000288923-DATIM-Data-Exchange-Instructions-and-Code-Lists (also see image below)

Most (or all) of the formats currently provided by DATIM are not supported out of the box by OCL, so these requests will be handled by the interoperability layer (i.e. OpenHIM) or in some scripting on the landing page

A plan is needed (google slides or doc is fine) for how each of the different requests will be handled by the clearinghouse.

![image](https://user-images.githubusercontent.com/1189689/29038884-2f9d145c-7b77-11e7-91c6-843bba9c94bd.png)

**Comment by jennifershivers** [comment]
We are including this process in the detailed step diagram we are creating for #20

**Comment by maurya** [comment]
Draft plan - 
https://docs.google.com/presentation/d/18EE7tTHHmg64XIIeWc38lfL_VoIpCTBhaLF_zBYGMhg/edit#slide=id.g243a0f1e14_0_12
