### ISSUE TITLE
Model org unit metadata model for OCL

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/DATIM-Metadata-Project#28]
This includes the global and country hierarchy and facilities.

Note that only countries that have agreed to make org unit data public will be published in the clearinghouse

**Comment by cmac35** [comment]
Draft ready for review: https://docs.google.com/presentation/d/1I-3ekVxHaxlpDl5fh8YstrE1yqjy30iVOqBH_flQheU/edit#slide=id.g24d2861eeb_0_18
