### ISSUE TITLE
Determine required changes to OCL architecture

### ISSUE THREAD

**Issue by jennifershivers** [OpenConceptLab/DATIM-Metadata-Project#3]
Determine if the OCL architecture needs to be revised to address near-term performance issues. Use New Relic monitoring logs and possibly profiling to inform decision. Also discuss with ThoughtWorks.

Areas to explore:
* Relationships used by mappings and collections
* Indexes for concepts and mappings because these queries are really slow
* Storing more of the data in Solr so that you don't have to query Mongo as well
* Array of resource versions that are stored in repository versions are very slow to update and sometimes have lost data during an update

Focus on the instability issues before focusing on the import

**Comment by paynejd** [comment]
Notes from discussion with Sunny from Thought Works:
(https://docs.google.com/document/d/1FktyoYRivNB5CIsLbiCAGDgsLAQyKXfvt0QbY-T9Ps0/edit#)

- Need a proper production configuration for Solr and Mongo with more resources -- both of these are currently dev set ups
- Paging issue was addressed
- Django needs to be upgraded - v1.6 did not support non-rel databases at the time
- Switching to RDBMS not necessarily a priority
- Redis introduced to manage asynchronous jobs -- mongo was not supported for these tasks
- Addressing instability/performance:
    - Configure the system to automatically refuse requests that are consuming too many resources -- in the future could potentially shift to asynchronous
    - Load balancing
    - Adding additional fields into Solr to reduce need to query mongo
- Haystack used for replication between solr and mongo
    - 2 options for replication -- real-time vs queued
    - Potential to replace haystack with a custom tunnel for replication
    - 3 points of potential issues: solr (e.g. during rebuilding the index), haystack, mongo (perhaps in the indexing)

**Comment by paynejd** [comment]
Remaining items in this list are long-term -- short-term items have been addressed
