### ISSUE TITLE
Model SIMS indicators

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/DATIM-Metadata-Project#31]
Jennifer to follow up on difference between 2.0 and 3.0

**Comment by cmac35** [comment]
Clarifying question for our conversation regarding SIMS: How is the data in the _sims v2 option sets_ file related to the data in the Above Site, Facility Based and Community Based data elements files (as there is no "option" field in these three files).

**Comment by cmac35** [comment]
Clarifying question for our conversation regarding SIMS: How often is the SIMS data published?

**Comment by cmac35** [comment]
Draft ready for review: Draft ready for review: https://docs.google.com/presentation/d/1I-3ekVxHaxlpDl5fh8YstrE1yqjy30iVOqBH_flQheU/edit#slide=id.g24d2861eeb_0_18

**Comment by paynejd** [comment]
Validate assumption: Implied connection between option sets and SIMS metadata that you can infer based on the name, but there is no column in SIMS metadata for option sets -- our assumption then is that we will not create mappings to link the SIMS option sets to the SIMS indicators. Carol to reach out to Vlad to confirm.

**Comment by paynejd** [comment]
@cmac35 Did we get the final question on the SIMS metadata answered? I noticed that Jennifer added notes to answer some of our previous questions in the comments on this ticket. If this question is not answered yet, can you reach out to Vlad?
