### ISSUE TITLE
Get DHIS2 account needed for integration with API

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/DATIM-Metadata-Project#32]
The account will need to be able to access the DATIM Global DHIS2 server via the API to fetch the following code lists:
* MER indicators (both targets and results)
* Disaggregation options
* Mechanisms
* SIMS indicators
* Global org units
* Public country-level units

We want the ability to fetch the full list and only records updated since a specified datetime.

We also want historical versions of these lists.

**Comment by jennifershivers** [comment]
we have accounts to test boxes and this should be adequate for now.
