### ISSUE TITLE
Compile metadata that will be imported without automation

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/DATIM-Metadata-Project#34]
For older versions of code lists that are not going to change, such as SIMS2.0 or previous periods of MER indicators (e.g. 2016Q1), the best approach may be to manually download these code lists and import them manually into OCL without the IOL.

Assigning Jennifer and Carol to this to confirm whether the above is true. Either way, let's develop the plan for the best way to get these imported into OCL, and if that involves manually compiling the metadata, we can get someone on our team to take care of the compilation step.

**Comment by jennifershivers** [comment]
The compilation is done on zendesk, here:  https://datim.zendesk.com/hc/en-us/articles/115002334246-DATIM-Data-Import-and-Exchange-Resources.  We should be able to import them once and then have them available.

**Comment by paynejd** [comment]
I think that the overarching question is for which code lists should we
plan on using a manual process vs. an automated process?

**Comment by jennifershivers** [comment]
I'm not sure they are really different lists.  They just have a different attribute.

**Comment by paynejd** [comment]
Okay. Let's discuss on our 1:30pm call. I'm actually beginning to think
that only mechanisms and org lists need to be automated, since the other
lists are published once and then are done.

**Comment by jennifershivers** [comment]
There can be "patches" that update indicators.  I agree that Mechansims and org lists are primary importance, but if we can automate indicators in the long run, we will be better off and saved from the manual updates they make.  (They don't change indicators much because then they have to change data entry forms.  The indicators are too tightly coupled with the forms.  So they do it as a patch right now. )

**Comment by paynejd** [comment]
Jennifer, let me restate that just to make sure that I'm understanding
correctly:

Instead of querying metadata from DATIM based on the dataset/code list, we
are aiming to query metadata from DATIM based on object type, which are
dataset (i.e. SIMS3.0 or Result 2017Q4), data element (i.e. indicator),
option (i.e. disaggregation), and then CategoryOptionCombo (which shows how
the above are linked). This approach will work as long as DHIS2 can return
all of the attributes that we need in each of the above queries and can
also filter each of those queries based on "last updated date".

Is that how you are thinking of this also?

**Comment by jennifershivers** [comment]
For getting updates from datim to put into OCL, I think we will be querying:  
1.  “indicators” and those have attributes that denote period and dataset.  
2.  sims - I think these may be in different data structure in DHSI2 than indicators, but we need to follow up.  
3.  Facilities 
4.  Mechanisms 

But we need to get down to that level next week as we dig into how to use the API.  

The presentation layer on ZenDesk is artificial and not indicative of the actual data structure.  
Jennifer 

@maurya

**Comment by paynejd** [comment]
FYI ideally all metadata is automated so this is being used to capture metadata that we will import manually during this phase of the project
