### ISSUE TITLE
Paging in oclapi rest requests seems to be broken

### ISSUE THREAD

**Issue by rkorytkowski** [OpenConceptLab/DATIM-Metadata-Project#39]
Running the following query takes 2 minutes and times out.

https://api.openconceptlab.org/orgs/CIEL/sources/CIEL/HEAD/mappings/?limit=25&verbose=true&page=6498

Running it 20 times or so at the same time kills the oclapi server.

I suspect an issue with paging results. It seems that the time is spent loading thousands of mappings to get to the 6429nth page, whereas it should only get 25 mappings out of db.

**Comment by rkorytkowski** [comment]
Ralates to #37.

**Comment by rkorytkowski** [comment]
Committed to jetstream branch in https://github.com/OpenConceptLab/oclapi/commit/9de170020f1926c2bb6cfc3470b4a0c619f60a40

Pushed to jetstream staging and production.

My fix may break some searches, which rely on searching for fields of a mapping, which are not in solr. I don't know, if there are any searches like that used anywhere in the app. If we see any such broken searches, we will basically need to put more fields into solr index...

**Comment by paynejd** [comment]
There are searches on several mapping fields as shown in the API wiki,
including owner, owner type, source, and concept name and ID for both the
from and to concepts and the map type. Several of those are returned as
facets by solr so they would have to be in the index. Concept names and IDs
may be handled differently.

**Comment by rkorytkowski** [comment]
Do you refer to https://github.com/OpenConceptLab/oclapi/wiki/mappings#search-and-filter-behavior ? If yes, then I verified that all searches except one work before and after my fix. The one, which doesn't work is querying by concept name e.g. https://api.openconceptlab.org/mappings/?concept=Disorder%20of%20Lymphatic%20System (without my fix) and https://oclapi.openmrs.org/mappings/?concept=Disorder%20of%20Lymphatic%20System (with my fix).

Should I file a bug?

**Comment by paynejd** [comment]
Yes please file a bug
