### ISSUE TITLE
define and design the mechanism refresh transaction 

### ISSUE THREAD

**Issue by jennifershivers** [OpenConceptLab/DATIM-Metadata-Project#45]
Design and document the mechanism trans

- Determine DHIS2 API / SQL view to use
- Determine the OCL import API / Script
- Map dhis2 to OCL
- Determine mediator requirements

**Comment by paynejd** [comment]
This is updated using the new DHIS2 metadata APIs. Includes step-by-step instructions for initial setup and import and subsequent imports, and daily maintenance processes.

@maurya Please review!

**Comment by maurya** [comment]
Hi Jon, 

From technical requirements, the process looks good! I have modified the initial import to have created field to make sure we handle newly created mechanisms as well (This might be handled using last imported but it is better to use created date for a check)

I am not sure if you need to save the Partners and Agencies as individual objects.

We might be able to use the existing Shell Script Mediator to automate if you have all the steps in a single script.

**Comment by paynejd** [comment]
Final design here: https://docs.google.com/presentation/d/18EE7tTHHmg64XIIeWc38lfL_VoIpCTBhaLF_zBYGMhg/edit#slide=id.g1fe87b65c6_0_0
