### ISSUE TITLE
Account for OCL

### ISSUE THREAD

**Issue by maurya** [OpenConceptLab/DATIM-Metadata-Project#46]
Determine what account and privileges are required for the user to do the import metadata into OCL

**Comment by maurya** [comment]
@paynejd , can you give some insight on the account needed?

**Comment by paynejd** [comment]
To perform an import in OCL, you simply need an account with edit
privileges on a repository. To do this, you can either be a member of an
organization that owns a repository, or you can create a user repository
from your user profile page.

To use the API, you need to create a user account on OCL and use your API
token that is on your user profile page.

The scripts I use for importing into OCL are located in this repo:
https://github.com/OpenConceptLab/ocl_import/

**Comment by paynejd** [comment]
@maurya To summarize, let's decide on the name of a user that we want to add as a member of the PEPFAR organization that we will use to run the imports. We can then create that user on each environment.
