### ISSUE TITLE
DHIS2 API Requests for all metadata (sqlviews)

### ISSUE THREAD

**Issue by maurya** [OpenConceptLab/DATIM-Metadata-Project#49]
We need a DHIS2 SqlView that can retrieve all the indicators similar to mechanisms

**Comment by paynejd** [comment]
These are the queries we want to be able to run against Global DATIM DHIS2, both as the “full” set and with “last updated” timestamp:

Primary metadata sets:
* Unique list of MER indicators across all periods and types (result/target)
* Unique list of disaggregation options used across MER indicators
* List of public org units and facilities
* Unique list of SIMS indicators
* Unique list of SIMS option sets
* Unique list of funding mechanisms
* Unique list of tiered site support options

Metadata that describes grouping and relationships between the above metadata sets:

- List of datasets that includes the name, period (e.g. COP16 FY17Q1) and type (i.e. result, target)
- Mapping of datasets to MER indicators
- Mapping of disaggregations to MER indicators
- List of SIMS versions
- Mapping of SIMS indicators to SIMS versions
- Mapping of SIMS indicators to SIMS option sets
- Mapping of mechanisms to org units?

Question: Can we get the full indicator definitions (incl. narrative descriptions) from DHIS2 or are these only in PDF form? How can we support PEPFAR in automating the descriptions as well?

**Comment by jennifershivers** [comment]
SQL Views will be placed here:  https://docs.google.com/document/d/1FHJcCdZoto52drw4WKLsDvpsnEMU6up8lrOUHAU2Ppk/edit
@maurya @cmac35 @paynejd

**Comment by paynejd** [comment]
@cmac35 @maurya and me to meet next week to evaluate existing sqlviews and create new ones

**Comment by paynejd** [comment]
@maurya let's identify a couple of views that we can start working with, even if we are defining the final views for integration.

Here are some relevant SqlViews that already exist on the test server (and presumably on production as well):
* A list of Datasets - https://test3.global.datim.org/dhis-web-maintenance-dataadmin/exportSqlView.action?id=2372001
* A view of Mechanism with UID - https://test3.global.datim.org/dhis-web-maintenance-dataadmin/exportSqlView.action?id=5477342
* Mechanisms partners agencies OUS Start End - https://test3.global.datim.org/dhis-web-maintenance-dataadmin/exportSqlView.action?id=8064814
* Category option combo overview - https://test3.global.datim.org/dhis-web-maintenance-dataadmin/exportSqlView.action?id=3211654

Many MER-specific views:
![image](https://user-images.githubusercontent.com/1189689/29675798-3ede21f4-88c4-11e7-81df-1de7e823839f.png)

**Comment by paynejd** [comment]
@maurya to work from the SqlViews currently used on the ZenDesk page back to the configuration in dhis2 to better understand how we can modify to get the fields we need.

@paynejd to more fully specify the fields that we need for each of the queries we want to execute.

**Comment by paynejd** [comment]
Update on progress:
* We have switched to using the DHIS2 Metadata API instead of SqlViews -- these have the advantage of not needing to be maintained the way SqlViews do, and we also have complete flexibility on the fields that are returned
* Metadata API calls have been developed for the initial import of mechanisms and MER indicators

Remaining:
* Metadata API calls for initial import of SIMS 3.0 and SIMS 2.0
* API calls for subsequent imports using lastUpdated filters

**Comment by paynejd** [comment]
Completed:
* Metadata API calls for initial import of SIMS 3.0 and SIMS 2.0

Remaining:
* API calls for subsequent imports using lastUpdated filters
