### ISSUE TITLE
Install mediators and configure the OpenHim to support sync transactions

### ISSUE THREAD

**Issue by jennifershivers** [OpenConceptLab/DATIM-Metadata-Project#51]
Install mediators and configure the OpenHim to support fr transactions

**Comment by paynejd** [comment]
Note that @maurya completed a beta of the sync mediator for SIMS. All sync scripts will be ready soon and can be implemented at the same time within OpenHIM. Moving this ticket to Milestone 5

**Comment by paynejd** [comment]
Officially closed out!
