### ISSUE TITLE
Implement Data Transformation scripts in medata-sync-mediator

### ISSUE THREAD

**Issue by maurya** [OpenConceptLab/DATIM-Metadata-Project#53]
Need to implement scripts from Carol to transform csv data to OCL Json

**Comment by paynejd** [comment]
Mediator created and implemented for MER.

@maurya You can now implement this for mechanisms too -- see datimshowmechanisms.py. Note that you should also update and test the code for datimshowmer.py too, as some small changes were made

Still to be completed:
* SIMS (using new code, which I'm still completing)
* Tiered Site Support (not done yet)
