### ISSUE TITLE
Deploy ocl_web to Jetstream

### ISSUE THREAD

**Issue by bmamlin** [OpenConceptLab/DATIM-Metadata-Project#57]
Once ocl_web is dockerized (#15) and oclapi has been deployed to Jetstream (#56), deploying ocl_web to Jetstream should be straightforward (essentially repeating the process used for ocl_api).

ocl_web should be deployed to a medium (16 GB) server in Jetstream. The corresponding ticket within ITSM is [ITSM-4018](https://issues.openmrs.org/browse/ITSM-4018).

**Comment by rkorytkowski** [comment]
Any reason to deploy ocl_web to a different server than ocl_api? It seems like a waste of resources... ocl_web could be run on the same server as ocl_api or some significantly smaller instance, but sharing it with ocl_api sounds like the best way to utilize resources. Remember we do need to have staging and qa in addition to production environment, which would mean 6 servers... I suggested 4 servers divided as follows:
1) m1.medium for openconceptlab.org (api and web)
2) m1.medium for staging.openconceptlab.org (api and web)
3) m1.small for qa.openconceptlab.org (api and web)
4) m1.small for GoCD (CI)

**Comment by paynejd** [comment]
Combining ocl_web and ocl_api is how we currently do it and should be fine
moving forward.

Keep in mind that we will also be adding OpenHIM to each of the
environments for the interoperability layer

**Comment by bmamlin** [comment]
The primary reason for separating web from api servers would be to avoid competition for resources – i.e., api slowing down web responses or vice versa (or to reduce ambiguity when debugging performance/latency issues). Other reasons might include scalability (e.g., running multiple web instances against a single api instance) and reliability (e.g., running servers in separate locations – some in Indiana and some in Texas).

These may not be enough of a reason to separate at this stage.

I think the most important thing is that these (web & api) are configured as separate services in terrraform. Whether or not we choose to currently colocate them in the infrastructure should be an arbitrary decision based on their requirements and not an assumption made by OCL (i.e., we should not be writing any configurations or code in OCL repos that assumes api & web are on the same server).

**Comment by rkorytkowski** [comment]
Work completed in the jetstream branch.
