### ISSUE TITLE
Design indicator model for OCL

### ISSUE THREAD

**Issue by jennifershivers** [OpenConceptLab/DATIM-Metadata-Project#6]

**Comment by cmac35** [comment]
Draft as of 8/7/17
[DATIM Metadata - Open Concepts Lab (OCL) Data Model 080717.pptx](https://github.com/OpenConceptLab/DATIM-Metadata-Project/files/1208665/DATIM.Metadata.-.Open.Concepts.Lab.OCL.Data.Model.080717.pptx)

Next Steps:
Alter Sample Indicators on OCL Staging to match proposed Model
Add additional data to OCL Staging 
Add screenshots from OCL to PowerPoint
Distribute for review

**Comment by cmac35** [comment]
Draft ready for review: Draft ready for review: https://docs.google.com/presentation/d/1I-3ekVxHaxlpDl5fh8YstrE1yqjy30iVOqBH_flQheU/edit#slide=id.g24d2861eeb_0_18
