### ISSUE TITLE
determine where to install the OpenHIM

### ISSUE THREAD

**Issue by jennifershivers** [OpenConceptLab/DATIM-Metadata-Project#60]

**Comment by paynejd** [comment]
Maurya / Burke to f/up

**Comment by maurya** [comment]
Will be starting with a small JetStream Server - we will migrate to medium if needed. I will be testing the install separately and be updating the ITSM ticket with what needs to be done to get the OpenHIM server ready.
https://issues.openmrs.org/browse/ITSM-4023
