### ISSUE TITLE
OCL API to get specific "extra" attribute fails with exception

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/DATIM-Metadata-Project#72]
I just tested on staging and unfortunately I'm seeing a similar error. These queries work as expected:

https://api.staging.openconceptlab.org/orgs/PEPFAR/sources/MER-Indicator/concepts/GEND-GBV-PEP-N-DSD-TARGET/
https://api.staging.openconceptlab.org/orgs/PEPFAR/sources/MER-Indicator/concepts/GEND-GBV-PEP-N-DSD-TARGET/extras/

However this query fails with a crazy exception:

https://api.staging.openconceptlab.org/orgs/PEPFAR/sources/MER-Indicator/concepts/GEND-GBV-PEP-N-DSD-TARGET/extras/Numerator/

I also tried querying with the specific concept version and this works as expected:

https://api.staging.openconceptlab.org/orgs/PEPFAR/sources/MER-Indicator/concepts/GEND-GBV-PEP-N-DSD-TARGET/591c83501bee0d004a3b2f52/extras/

But again this does not work:

https://api.staging.openconceptlab.org/orgs/PEPFAR/sources/MER-Indicator/concepts/GEND-GBV-PEP-N-DSD-TARGET/591c83501bee0d004a3b2f52/extras/Numerator/

**Comment by davetrig** [comment]
When I picked this back up to look at over the weekend, I found that the examples given above no longer generated the error.  I pulled the latest commits from oclapi/master into my fork, and again confirmed that this issue no longer seems to exist.

Whatever changes were recently commited to oclapi seem to have fixed this issue as well.

**Comment by paynejd** [comment]
Tested and it does work correctly! closing this out
