### ISSUE TITLE
Plan to automate landing page

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/DATIM-Metadata-Project#76]
Currently updating the landing page is a manual process. What would it entail to automate this page? Are we missing any information?

**Comment by cmac35** [comment]
Plan document located here: https://drive.google.com/open?id=1qIuTdYZiPpkElRaUkWoLY7EUNvn2x9neKnXI4YRipGo

**Comment by paynejd** [comment]
Closing this ticket and wrapping into #75
