### ISSUE TITLE
Customer support & troubleshooting plan

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/DATIM-Metadata-Project#77]

**Comment by jennifershivers** [comment]
Added a BaseCamp TODO for Jamie to help us with this.

**Comment by jennifershivers** [comment]
Met with Jamie.  we have a base plan.  There will be a link on the main clearinghouse page that will go to a help email.  More details will be worked out when Jamie is back from vacation.

**Comment by paynejd** [comment]
Support approach drafted here: https://docs.google.com/document/d/1Omvu8oZegVQ6FDq0SB02rSckH29xBjWJxRoH09WsjVY/edit#heading=h.envsncszirli
