### ISSUE TITLE
Determine strategy for facility data

### ISSUE THREAD

**Issue by jennifershivers** [OpenConceptLab/DATIM-Metadata-Project#8]
We need to determine how we will handle facility metadata.  

### 1) use OCL 
- CON might not be best fit as versioning and other features may not apply 
-CON  - does OCL currently support accounts that can limit viewing access?  
- PRO mapping does apply in the future 
### 2) Use FR
 - PRO uses another OHIE component 
- CON adds another component at this early phase in the project 
- Need to determine what best meets requirements and longer-term vision
### 3) Use current DHIS2 for initial deployment 
- PRO can probably deploy in similar manner as zen desk page 
- CON - doesn't show PEPFAR that we are making progress on this data 
- PRO - limits scope for us

**Comment by jennifershivers** [comment]
Based upon conversations with Jon, Paul and Jennifer.  The team will move forward with OCL to provide facilities (as a clearinghouse).  Curation will still need to be done in a FR.

**Comment by paynejd** [comment]
Moving this ticket to "Done" -- creating new ticket for creating the org unit model
