### ISSUE TITLE
User testing plan

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/DATIM-Metadata-Project#81]
Testing will probably begin in early September. Let's create a quick plan for how we will do this.

**Comment by jennifershivers** [comment]
1)  Proposed strategy for testing new Wiki page links (run the link from DATIM and view the results and then run the link from OCL and compare)  

2)  Proposed strategy for testing that concepts have been loaded into OCL (use SQL views to get the data from DATIM and then compare to OCL?)  

@paynejd These are my initial thoughts.

**Comment by paynejd** [comment]
@jennifershivers Good list. One more lower level test:
* Response codes from (1) DHIS2 Metadata API queries, (2) conversion scripts, (3) imports (either in test mode, or to a test server)

@rkorytkowski @maurya Any additional ideas for testing? Also, recommendations for the best way to implement these tests?

**Comment by jennifershivers** [comment]
Looked at gherkin descriptions being used by DHI2 team.  Most things I saw were user initiated.  They said they had API examples.  Need to look for those. 
Started setting up a process to write Gherkin test descriptions.

**Comment by jennifershivers** [comment]
https://docs.google.com/document/d/1Tw2Q7-EzRS1AraVV3tuwvcx75Svr8W49Cc3MCNq5YiQ/edit

**Comment by jennifershivers** [comment]
Ready for input and review @paynejd @cmac35 @maurya

**Comment by paynejd** [comment]
Completed review and closing this out. Work will continue in #148 and #123
