### ISSUE TITLE
Write CSV to JSON conversion scripts

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/DATIM-Metadata-Project#85]
This has been started based on what's coming out of ZenDesk, and it may change when using our updated queries from DHIS2

These scripts will be stored as code in this repo:
https://github.com/OpenConceptLab/DATIM-Metadata-Project/

**Comment by cmac35** [comment]
Added folder, and .py to convert csv to json for datasets/collections. Also included a csv of datasets from the "A list of Datasets" SQL View [https://test3.global.datim.org/dhis-web-maintenance-dataadmin/exportSqlView.action?id=2372001](url)

Code folder here:
https://github.com/OpenConceptLab/DATIM-Metadata-Project/tree/master/metadata/Datasets

**Comment by paynejd** [comment]
Closing this out -- turns out that we will not be going with the CSV-converter approach...
