### ISSUE TITLE
Write sync scripts for PEPFAR metadata

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/DATIM-Metadata-Project#86]
This has been started based on what's coming out of ZenDesk, and it may change when using our updated queries from DHIS2

These scripts will be stored as code in this repo:
https://github.com/OpenConceptLab/DATIM-Metadata-Project/

**Comment by jennifershivers** [comment]
https://docs.google.com/presentation/d/18EE7tTHHmg64XIIeWc38lfL_VoIpCTBhaLF_zBYGMhg/edit#slide=id.g1fe87b65c6_0_0

**Comment by paynejd** [comment]
Found and tested existing DeepDiff Python module that will work for our scripts with no modifications required! I have started to incorporate into the SIMS script.

**Comment by paynejd** [comment]
Completed:
* MER
* Mechanisms

Nearly completed:
* SIMS

Next up:
Tiered Site Support

**Comment by paynejd** [comment]
Closing this out -- SIMS and Tiered Site Support moving to a new ticket
