### ISSUE TITLE
Fix SSL on existing OCL servers

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/DATIM-Metadata-Project#87]
We are using the existing servers to perform test imports and also Ethiopia is still using production -- the SSL certificates are currently expired on all subdomains:

www.openconceptlab.org
api.openconceptlab.org
staging.openconceptlab.org
api.staging.openconceptlab.org
showcase.openconceptlab.org
api.showcase.openconceptlab.org
gocd.openconceptlab.org

**Comment by paynejd** [comment]
Based on how quickly we are moving, we probably only need to fix staging and production -- no need to do showcase and gocd

**Comment by paynejd** [comment]
GoCD on the showcase server is still having trouble but everything else is now a go thanks to @bmamlin !

**Comment by bmamlin** [comment]
I managed to get gocd fixed as well. It was an issue with the nginx configuration.

For the record, I fixed all the existing servers and set up cerbot to auto-renew by adding this file with permissions 755:

**/etc/cron.weekly/certbot-renew**
```
#!/bin/sh
set -e

certbot renew -q --post-hook "service nginx reload"
```

I also tweaked the nginx configuration to use this pattern for non-SSL connections to support certbot challenge and redirect all other requests to SSL:
```
server {
    listen 80;
    server_name <subdomain>.openconceptlab.org;
    location '/.well-known/acme-challenge' {
        default_type "text/plain";
        root        /var/www/openconceptlab;
    }
    location / {
        return 301 https://$host$request_uri;
    }
}
```
