### ISSUE TITLE
Move DNS to new servers

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/DATIM-Metadata-Project#94]

**Comment by paynejd** [comment]
@rkorytkowski @bmamlin Please let me know the IPs for DNS configuration for the following:

* openconceptlab.org, www.openconceptlab.org
* api.openconceptlab.org
* staging.openconceptlab.org
* api.staging.openconceptlab.org
* qa.openconceptlab.org
* api.qa.openconceptlab.org

**Comment by rkorytkowski** [comment]
I have opened up https://issues.openmrs.org/browse/ITSM-4041 (restricted) to address this. I'll get back to you once I hear what is the best approach since we also need SSL for those.

**Comment by rkorytkowski** [comment]
Cintia's reply:

It shouldn't be hard So, for each one of the three servers we need to do:
1) change the DNS records to ANAME/CNAME for (narok\|nakuru\|nairobi).openmrs.org.
2) change docker env variables to use the new urls; commit and push
3) change host_vars in ansible to the new urls
4) and run ansible

Order is pretty important here. But there will be downtime between 1) and 4).So it's a matter of how to schedule it. If Jonathan is ok about giving me the credentials for godaddy, I can do it from there. If here's not OK with that, I'd say we can migrate it to dnsmadeeasy (you still have access to that, right?), and then I continue from there.
--

**Comment by rkorytkowski** [comment]
@paynejd, so the question is how you want to handle that? Do you want to change DNS entries yourself, grant us access to godaddy or migrate the domain to dnsmadeeasy?

**Comment by paynejd** [comment]
@rkorytkowski I will change DNS myself for this round of changes. Assuming that we will switch to Dnsmadeeasy at some point, but not a current priority. Please let me know what changes to make.

Is there additional configuration that needs to be done since each sub domain needs to have an SSL certificate?

**Comment by rkorytkowski** [comment]
You need to:
edit openconceptlab.org to point to nairobi.openmrs.org
edit api.openconceptlab.org to point to nairobi.openmrs.org
edit www.openconceptlab.org to point to nairobi.openmrs.org
edit staging.openconceptlab.org to point to nakuru.openmrs.org
edit api.staging.openconceptlab.org to point to nakuru.openmrs.org
edit qa.openconceptlab.org to point to narok.openmrs.org
edit api.qa.openconceptlab.org to point to narok.openmrs.org

It takes time for DNS changes to propagate, but there's a trick, which we can use to make it happen quickly. You need to set TTL in your DNS provider to a lower value e.g. 60 seconds. Once we are done with the move you can switch it back to normal. You need to lower TTL as soon as possible (now) so it gets propagated before we do the actual move.

We'll handle the SSL certiciates setup.

**Comment by rkorytkowski** [comment]
Completed! 

Let's keep the old servers running for a week or so just in case we need to revert to using them quickly.

I also disabled GoCD and it is not building the project any longer. http://ci.openconceptlab.org/ now points to Bamboo. 

showcase.openconceptlab.org is no longer available. Please use qa.openconceptlab.org from now on.

**Comment by rkorytkowski** [comment]
Merged jetstream branch into master for api and web projects. Created digitalocean branch before that just in case we need to revert.
