### ISSUE TITLE
Validation of concepts is extra slow

### ISSUE THREAD

**Issue by rkorytkowski** [OpenConceptLab/DATIM-Metadata-Project#95]
The reason is that the validator loads all concept names into memory to later check for uniqueness, whereas it should search solr index for concept with matching names...

It makes imports and virtually any updates to concepts slow when the number of concepts grows.

See https://github.com/OpenConceptLab/oclapi/blob/master/django-nonrel/ocl/concepts/validators.py#L30-L47

**Comment by rkorytkowski** [comment]
Committed in https://github.com/OpenConceptLab/oclapi/commit/66fb7079a88dce2f47c15217bdf9c895bcc3443e

The solr index includes only display_name for searching, which is not enough for validation. I still load all concept names into memory, but made the query much more efficient. It reduced run time by 4-5x.

**Comment by paynejd** [comment]
The solr index was updated by thought works to include all concept names
not just display name, so theoretically it should be possible to use it for
validation.

**Comment by rkorytkowski** [comment]
Interesting. I don't see that in code or I'm looking in the wrong place...  https://github.com/OpenConceptLab/oclapi/blob/master/django-nonrel/ocl/concepts/search_indexes.py#L14-L15

**Comment by paynejd** [comment]
Originally only the display_name was indexed, then TW expanded it to search all names/synonyms. It appears that they did this by just expanding the "display_name" field in Solr to include all of the names, so it isn't apparent in the code.

**Comment by rkorytkowski** [comment]
I'll look into that again.

**Comment by rkorytkowski** [comment]
Approached it differently by using a mongodb index. Committed in https://github.com/OpenConceptLab/oclapi/commit/a6ad0d485f88200f2d139f24003361e1f87c1310
