### ISSUE TITLE
Finding mapping by concept name does not work

### ISSUE THREAD

**Issue by rkorytkowski** [OpenConceptLab/DATIM-Metadata-Project#96]
Finding mapping by concept name does not work e.g. https://api.openconceptlab.org/mappings/?concept=Disorder%20of%20Lymphatic%20System

**Comment by davetrig** [comment]
Putting the search term in quotes yields the correct result.  e.g. https://api.openconceptlab.org/mappings/?concept="Disorder%20of%20Lymphatic%20System"

**Comment by rkorytkowski** [comment]
Could you please mention that in docs at https://github.com/OpenConceptLab/oclapi/wiki/mappings#search-and-filter-behavior ?

**Comment by paynejd** [comment]
I went ahead and added this to the documentation so that we can close this one out
